[project]
name = "oskemenbus-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
]
